name: build
on: 
  push:
  schedule:
    - cron: '0 13 * * 1'
jobs:
 
  build:
    runs-on: ubuntu-latest
    #needs: clear
    steps:
      - uses: actions/checkout@v3
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull
          curl -L -H "Cache-Control: no-cache" -o main.zip https://github.com/benbusby/whoogle-search/archive/refs/heads/main.zip
          unzip main.zip 
          rm -rf main.zip
          git add .
          git commit -m "$(date "+%Y%m%d-%H%M")"
          git push 
